//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// Copyright © dev-cetera.com & contributors.
//
// The use of this source code is governed by an MIT-style license described in
// the LICENSE file located in this project's root directory.
//
// See: https://opensource.org/license/mit
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import 'package:df_gen_core/df_gen_core.dart';
import 'package:df_generate_dart_models_core/df_generate_dart_models_core.dart';
import 'package:df_generate_dart_models_core/df_generate_dart_models_core_utils.dart';

import 'extract_insights_from_file.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

/// Walks every Dart file under [inputPath], extracts each
/// `@GenerateDartModel` annotation, and writes one DBML file describing the
/// schema as a single `Table` per model plus trailing `Ref:` lines for the
/// foreign keys captured in `references:`.
///
/// Output is dialect-agnostic DBML — emit dialect-specific SQL downstream
/// with `dbml2sql --postgres` or `dbml2sql --sqlite`.
Future<void> generateDbml(
  List<String> args, {
  String defaultOutputPath = 'schema.dbml',
}) async {
  Log.enableReleaseAsserts = true;

  const OUTPUT_PATH = OptionParam(
    name: 'output',
    defaultsTo: 'schema.dbml',
  );

  final parser = CliParser(
    title: 'dev-cetera.com',
    description:
        'Generates a DBML schema file from classes annotated with '
        '@GenerateDartModel. The PG_*-/SQLITE_*- prefixes on fieldType drive '
        'column types, `references:` drives FK Ref lines, and `primaryKey:` '
        'drives the `[pk]` constraint.',
    example: 'generate-dbml -i lib/src/db_models -o schema.dbml',
    additional:
        'For contributions, error reports and information, visit: '
        'https://github.com/dev-cetera.',
    params: [
      DefaultFlags.HELP.flag,
      DefaultOptionParams.INPUT_PATH.option.copyWith(
        defaultsTo: FileSystemUtility.i.currentDir,
      ),
      DefaultOptionParams.DART_SDK.option,
      OUTPUT_PATH,
    ],
  );

  final (argResults, argParser) = parser.parse(args);

  if (argResults.flag(DefaultFlags.HELP.name)) {
    Log.printCyan(parser.getInfo(argParser));
    exit(ExitCodes.SUCCESS.code);
  }

  late final String inputPath;
  late final String? dartSdk;
  late final String outputPath;
  try {
    inputPath = argResults.option(DefaultOptionParams.INPUT_PATH.name)!;
    dartSdk = argResults.option(DefaultOptionParams.DART_SDK.name);
    outputPath = argResults.option(OUTPUT_PATH.name) ?? defaultOutputPath;
  } catch (_) {
    Log.printRed(
      'Missing required args! Use --help flag for more information.',
    );
    exit(ExitCodes.FAILURE.code);
  }

  final analysisContextCollection = createDartAnalysisContextCollection(
    {inputPath},
    dartSdk,
  );

  Log.printWhite('Looking for Dart files in $inputPath...');
  final stream = PathExplorer(inputPath).exploreFiles().where(
        (e) => _isAllowedFileName(e.path),
      );

  final allInsights = <ClassInsight<GenerateDartModel>>[];
  try {
    await for (final finding in stream) {
      final insights = await extractInsightsFromFile(
        finding.path,
        analysisContextCollection,
      );
      allInsights.addAll(insights);
    }
  } catch (e) {
    Log.printRed('Failed while reading: $e');
    exit(ExitCodes.FAILURE.code);
  }

  Log.printWhite(
    'Found ${allInsights.length} model(s); emitting DBML to $outputPath...',
  );

  final buffer = StringBuffer();
  buffer.writeln('// Generated by df_generate_dart_models.');
  buffer.writeln('// Source: ${PathUtility.i.localBaseName(inputPath)}');
  buffer.writeln();

  final refLines = <String>[];

  for (final insight in allInsights) {
    _emitTable(insight, buffer, refLines);
    buffer.writeln();
  }

  if (refLines.isNotEmpty) {
    for (final line in refLines) {
      buffer.writeln(line);
    }
  }

  await FileSystemUtility.i.writeLocalFile(outputPath, buffer.toString());
  Log.printGreen('✔ Wrote ${allInsights.length} table(s) to $outputPath');
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

void _emitTable(
  ClassInsight<GenerateDartModel> insight,
  StringBuffer buffer,
  List<String> refLines,
) {
  final tableName = _tableNameFor(insight);

  buffer.writeln('Table $tableName {');

  for (final field in insight.fields) {
    final columnName = _columnNameFor(insight, field);
    final sqlType = _sqlTypeFor(field);
    final notes = <String>[];

    if (field.primaryKey == true) notes.add('pk');
    if (field.nullable != true && field.primaryKey != true) {
      notes.add('not null');
    }

    final references = _referencesNameFor(field);
    if (references != null) {
      // FK target column defaults to `id` — the conventional primary key
      // of every model in this codebase.
      notes.add('ref: > $references.id');
    }

    final description = field.description;
    if (description != null && description.isNotEmpty) {
      notes.add("note: '${_escapeDbmlString(description)}'");
    }

    final noteSegment = notes.isEmpty ? '' : ' [${notes.join(', ')}]';
    buffer.writeln('  $columnName $sqlType$noteSegment');
  }

  buffer.writeln('}');
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

String _tableNameFor(ClassInsight<GenerateDartModel> insight) {
  final raw = insight.annotation.className ??
      insight.className.replaceFirst(RegExp(r'^[_$]+'), '');
  // ModelAccount → accounts (drop the Model prefix, snake-case, pluralise
  // minimally with a trailing 's'). The pluralisation is naive; users can
  // override by setting className: explicitly on the annotation.
  final stripped = raw.startsWith('Model') ? raw.substring(5) : raw;
  return stripped.toSnakeCase() + (stripped.endsWith('s') ? '' : 's');
}

String _columnNameFor(
  ClassInsight<GenerateDartModel> insight,
  DartField field,
) {
  final path = field.fieldPath;
  if (path == null || path.isEmpty) return field.fieldName ?? 'unknown';
  return insight.stringCaseType.convertAll(path).join('_');
}

/// Derives the DBML column type from the `PG_*-`/`SQLITE_*-` prefix in
/// `fieldType`, falling back to a sensible default per the bare Dart
/// type when no dialect prefix is set.
String _sqlTypeFor(DartField field) {
  final raw = field.fieldType ?? 'dynamic';
  final dialectMatch = RegExp(
    r'^(?:PG|SQLITE)_(\w+(?:\([^)]*\))?(?:\[\])?)-',
  ).firstMatch(raw);
  if (dialectMatch != null) return dialectMatch.group(1)!;

  // Defaults for bare Dart types.
  final bare = raw.replaceAll('?', '');
  switch (bare) {
    case 'String':
      return 'text';
    case 'int':
      return 'bigint';
    case 'double':
      return 'double precision';
    case 'num':
      return 'numeric';
    case 'bool':
      return 'boolean';
    case 'DateTime':
      return 'timestamptz';
    case 'Uint8List':
      return 'bytea';
    case 'Uri':
      return 'text';
    case 'BigInt':
      return 'numeric';
    case 'Duration':
      return 'bigint';
  }
  // Map / List / Set / nested Models → jsonb by default.
  if (bare.startsWith('Map') ||
      bare.startsWith('List') ||
      bare.startsWith('Set') ||
      bare.startsWith('Iterable') ||
      RegExp(r'^(Model-?\w+|\w+-?Model)$').hasMatch(bare)) {
    return 'jsonb';
  }
  return 'text';
}

/// Maps a `references:` Type display name to the conventional table name.
/// The referenced model is named like `ModelUser`; we apply the same
/// table-name convention as [_tableNameFor].
String? _referencesNameFor(DartField field) {
  final ref = field.references;
  if (ref == null) return null;
  final raw = ref.toString();
  if (raw.isEmpty || raw == 'Object' || raw == 'dynamic') return null;
  final stripped = raw.startsWith('Model') ? raw.substring(5) : raw;
  return stripped.toSnakeCase() + (stripped.endsWith('s') ? '' : 's');
}

String _escapeDbmlString(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll('\n', ' ');

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

bool _isAllowedFileName(String e) {
  final lc = e.toLowerCase();
  return !lc.endsWith('.g.dart') && lc.endsWith('.dart');
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension _ClassInsightExtension on ClassInsight<GenerateDartModel> {
  Iterable<DartField> get fields {
    return annotation.fields?.whereType<TFieldRecord>().map((e) {
          return DartField.fromRecord(e);
        }).nonNulls ??
        const [];
  }

  StringCaseType get stringCaseType {
    return StringCaseType.values.valueOf(annotation.keyStringCase) ??
        StringCaseType.CAMEL_CASE;
  }
}
