// Asserts that each of the integration models generates the expected code
// shape for its dialect. The models themselves are regenerated by the standard
// generator pipeline; this test reads the resulting .g.dart files and verifies
// the right mapper output landed.
//
// To regenerate the .g.dart files for the dirs this test reads from:
//   dart run bin/df_generate_dart_models.dart \
//     -i test/integration/models -t templates/featured_v1.dart.md
//   dart run bin/df_generate_dart_models.dart \
//     -i test/integration/models_envelope -t templates/featured_v1.dart.md
//   dart run bin/df_generate_dart_models.dart \
//     -i test/integration/models_minimal -t templates/minimal_v1.dart.md

import 'dart:io';

import 'package:test/test.dart';

String _read(String name) => _readFrom('models', name);

String _readFrom(String dir, String name) {
  final f = File('test/integration/$dir/$name');
  if (!f.existsSync()) {
    throw StateError('missing generated file: $dir/$name. Did you run the '
        'generator? `dart run bin/df_generate_dart_models.dart '
        '-i test/integration/$dir -t templates/featured_v1.dart.md`');
  }
  return _unwrap(f.readAsStringSync());
}

/// Unwraps Dart-formatter line continuations so substring assertions can match
/// semantic expressions regardless of how the formatter chose to break them.
/// Joins each newline+indent into a single space, then strips whitespace before
/// `.` and `?.` so chained-method calls like `foo\n    .bar` or
/// `foo\n    ?.bar` both read as `foo.bar` / `foo?.bar`.
String _unwrap(String s) {
  s = s.replaceAll(RegExp(r'\n[ \t]*'), ' ');
  s = s.replaceAll(RegExp(r' +\?\.'), '?.');
  s = s.replaceAll(RegExp(r' +\.'), '.');
  s = s.replaceAll(RegExp(r' +'), ' ');
  return s;
}

void main() {
  group('Base types (DartCoreTypeMappers)', () {
    final code = _read('_model_base.g.dart');

    test('String fields use the coercive trim+nullIfEmpty chain', () {
      expect(code, contains('?.toString().trim().nullIfEmpty'));
    });

    test('int field uses letIntOrNull (Phase 1 coercion fix)', () {
      expect(code, contains('letIntOrNull(json?'));
    });

    test('double field uses letDoubleOrNull', () {
      expect(code, contains('letDoubleOrNull(json?'));
    });

    test('bool field uses letBoolOrNull', () {
      expect(code, contains('letBoolOrNull(json?'));
    });

    test('DateTime uses the coerce-to-string-first chain', () {
      expect(code, contains('DateTime.tryParse(a)?.toUtc()'));
    });

    test('Uri uses Uri.tryParse', () {
      expect(code, contains('Uri.tryParse(a)'));
    });

    test('BigInt uses BigInt.tryParse', () {
      expect(code, contains('BigInt.tryParse(a)'));
    });

    test('Equatable mixin is applied to the generated class', () {
      expect(code, contains('with EquatableMixin'));
      expect(code, contains('List<Object?> get props =>'));
    });

    test('FieldNames class is emitted', () {
      expect(code, contains('abstract final class ModelBaseFieldNames'));
    });
  });

  group('Postgres dialect (DartPostgresTypeMappers)', () {
    final code = _read('_model_pg_user.g.dart');

    test('PG_uuid-String forwards to the String coercion', () {
      expect(code, contains("id = json?['id']?.toString().trim().nullIfEmpty"));
    });

    test('PG_citext-String forwards to the String coercion', () {
      expect(
        code,
        contains("email = json?['email']?.toString().trim().nullIfEmpty"),
      );
    });

    test('PG_varchar(N) tolerates the size parameter', () {
      expect(
        code,
        contains(
          "displayName = json?['display_name']?.toString().trim().nullIfEmpty",
        ),
      );
    });

    test('PG_bigint-int forwards to letIntOrNull', () {
      expect(code, contains("loginCount = letIntOrNull(json?['login_count'])"));
    });

    test('PG_boolean-bool forwards to letBoolOrNull', () {
      expect(code, contains("isActive = letBoolOrNull(json?['is_active'])"));
    });

    test('PG_bytea-Uint8List passes bytes through (no base64)', () {
      expect(
        code,
        contains("avatarBytes = letAsOrNull<Uint8List>(json?['avatar_bytes'])"),
      );
    });

    test('PG_enum emits the bare valueOf call (no unknownEnumValue slot)', () {
      expect(
        code,
        contains(
          'AuthProviderKindType.values.valueOf'
          "(json?['auth_provider']?.toString())",
        ),
      );
    });

    test('PG_timestamptz uses the DateTime.tryParse chain', () {
      expect(code, contains('DateTime.tryParse(a)?.toUtc()'));
    });
  });

  group('Postgres nested model + jsonb + references', () {
    final code = _read('_model_pg_post.g.dart');

    test('jsonb-Map decodes via letMapOrNull', () {
      expect(code, contains("letMapOrNull<dynamic, dynamic>(json?['extra'])"));
    });

    test('jsonb-Model decodes via letMapOrNull then ModelXxx.fromJson', () {
      expect(
        code,
        contains("letMapOrNull<String, dynamic>(json?['metadata'])"),
      );
      expect(code, contains('ModelPostMetadata.fromJson(a)'));
    });

    test('jsonb-Map to-side uses jsonEncode + local alias (no stray p0)', () {
      expect(code, contains('extra0 ='));
      expect(code, contains('jsonEncode(a.map'));
      expect(code, isNot(contains('jsonEncode(p0!.map')));
    });

    test('jsonb-Model to-side uses jsonEncode(toJson())', () {
      expect(code, contains('jsonEncode(metadata!.toJson())'));
    });

    test('PG_enum on the post status uses the bare valueOf', () {
      expect(code, contains('PostStatusKindType.values.valueOf'));
    });

    test('native PG array decodes via letListOrNull', () {
      expect(code, contains("letListOrNull<dynamic>(json?['tags'])"));
    });
  });

  group('SQLite dialect (DartSqliteTypeMappers)', () {
    final code = _read('_model_sqlite_settings.g.dart');

    test('SQLITE_integer-bool forwards to letBoolOrNull (handles 0/1)', () {
      expect(
        code,
        contains(
          'notificationsEnabled = letBoolOrNull'
          "(json?['notifications_enabled'])",
        ),
      );
    });

    test('SQLITE_integer-bool emits 0/1 on write', () {
      expect(code, contains('notificationsEnabled! ? 1 : 0'));
    });

    test('SQLITE_epochms-DateTime decodes epoch ms', () {
      expect(
        code,
        contains('DateTime.fromMillisecondsSinceEpoch(a, isUtc: true)'),
      );
    });

    test('SQLITE_text-DateTime keeps the ISO 8601 chain', () {
      expect(code, contains('DateTime.tryParse(a)?.toUtc()'));
    });

    test('SQLITE_json-Map jsonEncodes with local alias (no stray p0)', () {
      expect(code, contains('jsonEncode(a.map'));
      expect(code, isNot(contains('jsonEncode(p0!.map')));
    });

    test('SQLITE_blob-Uint8List passes raw bytes', () {
      expect(
        code,
        contains("letAsOrNull<Uint8List>(json?['avatar_cache'])"),
      );
    });
  });

  group('Firestore dialect (DartFirestoreTypeMappers)', () {
    final code = _read('_model_firestore_doc.g.dart');

    test('FS_timestamp-DateTime converts via Timestamp.toDate().toUtc()', () {
      expect(code, contains('letAsOrNull<Timestamp>'));
      // The mapper now emits a single null-aware chain directly
      // `letAsOrNull<Timestamp>(...)?.toDate().toUtc()` — no intermediate
      // `final a = ...` binding.
      expect(code, contains('?.toDate().toUtc()'));
    });

    test('FS_timestamp-DateTime writes via Timestamp.fromDate', () {
      expect(code, contains('Timestamp.fromDate(capturedAt!.toUtc())'));
    });

    test('FS_server_timestamp-DateTime writes FieldValue.serverTimestamp()',
        () {
      expect(code, contains('FieldValue.serverTimestamp()'));
    });

    test('FS_geopoint-GeoPoint passes through', () {
      expect(code, contains("letAsOrNull<GeoPoint>(json?['location'])"));
    });

    test('FS_ref-String pulls .path off DocumentReference', () {
      expect(code, contains('letAsOrNull<DocumentReference>'));
      expect(code, contains('?.path'));
    });

    test('FS_blob-Uint8List unwraps Blob.bytes on read', () {
      expect(code, contains('letAsOrNull<Blob>'));
      expect(code, contains('?.bytes'));
    });

    test('FS_blob-Uint8List wraps in Blob() on write', () {
      expect(code, contains('Blob(thumbnail!)'));
    });

    test('back-compat: bare Timestamp still works', () {
      expect(
        code,
        contains("legacyStamp = letAsOrNull<Timestamp>(json?['legacyStamp'])"),
      );
    });
  });

  group('STRICT- direct casts', () {
    final code = _read('_model_strict_dto.g.dart');

    test('STRICT-String emits a direct as-cast', () {
      expect(code, contains("id = json?['id'] as String?"));
      expect(code, contains("name = json?['name'] as String?"));
    });

    test('STRICT-int routes through num for JSON num→int handling', () {
      expect(code, contains("count = (json?['count'] as num?)?.toInt()"));
    });

    test('STRICT-double routes through num', () {
      expect(code, contains("ratio = (json?['ratio'] as num?)?.toDouble()"));
    });

    test('STRICT-bool casts directly', () {
      expect(code, contains("active = json?['active'] as bool?"));
    });

    test('STRICT-DateTime parses without defensive chain', () {
      expect(
        code,
        contains("DateTime.parse(json?['createdAt'] as String).toUtc()"),
      );
    });

    test('STRICT-Uri parses directly', () {
      expect(code, contains("Uri.parse(json?['homepage'] as String)"));
    });

    test('STRICT to-side passes primitives through', () {
      expect(code, contains('final id0 = id;'));
      expect(code, contains('final name0 = name;'));
      expect(code, contains('final count0 = count;'));
    });
  });

  group('Thread (jsonb List<Model> + cross-model nesting)', () {
    final code = _read('_model_thread.g.dart');

    test('PG_jsonb-List<Model> uses letListOrNull on read', () {
      expect(code, contains("letListOrNull<dynamic>(json?['comments'])"));
    });

    test('list of model items invokes nested fromJson per element', () {
      // The collection mapper iterates and applies the per-element mapper.
      // For a model element, that's `ModelComment.fromJson(...)`.
      expect(code, contains('ModelComment.fromJson'));
    });

    test('jsonb-List<Model> to-side wraps each in toJson() + jsonEncodes', () {
      expect(code, contains('jsonEncode'));
      expect(code, contains('toJson()'));
    });

    test('the model still emits Equatable wiring', () {
      expect(code, contains('with EquatableMixin'));
    });

    test('fieldnames class includes the camelCased field names', () {
      expect(code, contains('static const creatorId = '));
      expect(code, contains('static const unreadCount = '));
      expect(code, contains('static const cacheToken = '));
    });
  });

  group('Envelope (bare nested-typed children, no DB prefix)', () {
    // Locks in the patterns compledo-style api_models depend on: typed
    // submodels round-trip cleanly without any PG_/SQLITE_/FS_ prefix when
    // declared via the String form (`'List<ModelEnvelopeChild>'`, etc.).
    final code = _readFrom('models_envelope', '_model_envelope.g.dart');
    final mapCode =
        _readFrom('models_envelope', '_model_envelope_map_values.g.dart');

    test('single nested model decodes via letMapOrNull + fromJson', () {
      expect(
        code,
        contains("letMapOrNull<String, dynamic>(json?['primary_child'])"),
      );
      expect(code, contains('ModelEnvelopeChild.fromJson'));
    });

    test('single nested model encodes via child.toJson()', () {
      expect(code, contains('primaryChild?.toJson()'));
    });

    test('List<Model> round-trips per element through fromJson/toJson', () {
      expect(code, contains("letListOrNull<dynamic>(json?['children'])"));
      // Inside the per-element map: letMapOrNull -> ModelEnvelopeChild.fromJson
      expect(code, contains('ModelEnvelopeChild.fromJson'));
      // To-side per-element toJson.
      expect(code, contains('children?.map'));
      expect(code, contains('p0?.toJson()'));
    });

    test('Set<Model> uses letSetOrNull on read and toSet/toList on write', () {
      expect(code, contains("letSetOrNull<dynamic>(json?['unique_children'])"));
      expect(code, contains('uniqueChildren?.map'));
    });

    test('List<String> applies the primitive coercion per element', () {
      expect(code, contains("letListOrNull<dynamic>(json?['tags'])"));
      expect(code, contains('p0?.toString().trim().nullIfEmpty'));
    });

    test('Map<String, Model> threads both K and V mappers per entry', () {
      expect(
        code,
        contains("letMapOrNull<dynamic, dynamic>(json?['children_by_id'])"),
      );
      // Both p0 (key=String) and p1 (value=Model) get their own mapper.
      expect(code, contains('p0?.toString().trim().nullIfEmpty'));
      expect(code, contains('ModelEnvelopeChild.fromJson'));
    });

    test('Map<String, DateTime> threads the DateTime mapper on values', () {
      expect(
        mapCode,
        contains("letMapOrNull<dynamic, dynamic>(json?['ticked_by'])"),
      );
      // The DateTime mapper coerces via toString().trim() then DateTime.tryParse.
      expect(mapCode, contains('DateTime.tryParse'));
      // Write-side toUtc().toIso8601String() per value.
      expect(mapCode, contains('p1?.toUtc().toIso8601String()'));
    });

    test('FieldNames \$values lists every declared field in order', () {
      // The Dart formatter wraps long list literals onto separate lines —
      // `_unwrap` collapses those back but leaves a single space inside the
      // brackets. Match the field sequence rather than the exact bracketing.
      expect(
        code,
        contains(
          'static const List<String> \$values = [ primaryChild, children, '
          'uniqueChildren, tags, childrenById ]',
        ),
      );
    });

    test('FieldNames \$primaryKey is null when no primary key declared', () {
      expect(code, contains('static const String? \$primaryKey = null'));
    });

    test('FieldNames \$foreignKeys is empty when none declared', () {
      expect(
        code,
        contains('static const Map<String, String> \$foreignKeys = {}'),
      );
    });
  });

  group('FieldNames metadata on a DB-shaped model (Thread)', () {
    final code = _read('_model_thread.g.dart');

    test('\$primaryKey resolves to the primary-key field-name constant', () {
      // Non-nullable declaration since a primary key exists — avoids the
      // unnecessary_nullable_for_final_variable_declarations lint.
      expect(code, contains('static const String \$primaryKey = id'));
    });

    test('\$foreignKeys maps the foreign-key field to its referenced class',
        () {
      expect(
        code,
        contains(
          "static const Map<String, String> \$foreignKeys = {creatorId: 'ModelPgUser'}",
        ),
      );
    });
  });

  group('Minimal template smoke', () {
    // The minimal template is intentionally narrower (no fromJson/toJson, no
    // FieldNames, no Equatable). This group just asserts the smoke fixture
    // generates code that still satisfies the minimal contract.
    final code = _readFrom('models_minimal', '_model_minimal_smoke.g.dart');

    test('class is a standalone DTO (no inheritance, no Equatable)', () {
      expect(code, contains('class ModelMinimalSmoke {'));
      expect(code, isNot(contains('extends Model')));
      expect(code, isNot(contains('EquatableMixin')));
    });

    test('emits the default constructor with required + optional params', () {
      // `id` and `active` are non-nullable -> `required`.
      expect(code, contains('required this.id'));
      expect(code, contains('required this.active'));
    });

    test('copyWith and copyWithout reuse the default constructor', () {
      expect(code, contains('ModelMinimalSmoke copyWith('));
      expect(code, contains('ModelMinimalSmoke copyWithout('));
      // copyWithout passes null for opted-out fields. The formatter spaces
      // the conditional `:`, so match the spaced form `id ? this.id : null`.
      expect(code, contains('id: id ? this.id : null'));
    });

    test('bang-getters apply only to non-nullable fields', () {
      expect(code, contains('String get id\$ => id!'));
      expect(code, contains('bool get active\$ => active!'));
      // Nullable fields keep nullable return type, no bang.
      expect(code, contains('int? get count\$ => count'));
      expect(code, contains('List<String>? get tags\$ => tags'));
    });
  });
}
