// Asserts that each of the integration models in test/integration/models/
// generates the expected code shape for its dialect. The models themselves
// are regenerated by the standard generator pipeline; this test reads the
// resulting .g.dart files and verifies the right mapper output landed.
//
// To regenerate the .g.dart files:
//   dart run bin/df_generate_dart_models.dart \
//     -i test/integration/models \
//     -t templates/featured_v1.dart.md

import 'dart:io';

import 'package:test/test.dart';

String _read(String name) {
  final f = File('test/integration/models/$name');
  if (!f.existsSync()) {
    throw StateError('missing generated file: $name. Did you run the '
        'generator? `dart run bin/df_generate_dart_models.dart '
        '-i test/integration/models -t templates/featured_v1.dart.md`');
  }
  return f.readAsStringSync();
}

void main() {
  group('Base types (DartCoreTypeMappers)', () {
    final code = _read('_model_base.g.dart');

    test('String fields use the coercive trim+nullIfEmpty chain', () {
      expect(code, contains('?.toString().trim().nullIfEmpty'));
    });

    test('int field uses letIntOrNull (Phase 1 coercion fix)', () {
      expect(code, contains('letIntOrNull(json?'));
    });

    test('double field uses letDoubleOrNull', () {
      expect(code, contains('letDoubleOrNull(json?'));
    });

    test('bool field uses letBoolOrNull', () {
      expect(code, contains('letBoolOrNull(json?'));
    });

    test('DateTime uses the coerce-to-string-first chain', () {
      expect(code, contains('DateTime.tryParse(a)?.toUtc()'));
    });

    test('Uri uses Uri.tryParse', () {
      expect(code, contains('Uri.tryParse(a)'));
    });

    test('BigInt uses BigInt.tryParse', () {
      expect(code, contains('BigInt.tryParse(a)'));
    });

    test('Equatable mixin is applied to the generated class', () {
      expect(code, contains('with EquatableMixin'));
      expect(code, contains('List<Object?> get props =>'));
    });

    test('FieldNames class is emitted', () {
      expect(code, contains('abstract final class ModelBaseFieldNames'));
    });
  });

  group('Postgres dialect (DartPostgresTypeMappers)', () {
    final code = _read('_model_pg_user.g.dart');

    test('PG_uuid-String forwards to the String coercion', () {
      expect(code, contains("id = json?['id']?.toString().trim().nullIfEmpty"));
    });

    test('PG_citext-String forwards to the String coercion', () {
      expect(
        code,
        contains("email = json?['email']?.toString().trim().nullIfEmpty"),
      );
    });

    test('PG_varchar(N) tolerates the size parameter', () {
      expect(
        code,
        contains(
          "displayName = json?['display_name']?.toString().trim().nullIfEmpty",
        ),
      );
    });

    test('PG_bigint-int forwards to letIntOrNull', () {
      expect(code, contains("loginCount = letIntOrNull(json?['login_count'])"));
    });

    test('PG_boolean-bool forwards to letBoolOrNull', () {
      expect(code, contains("isActive = letBoolOrNull(json?['is_active'])"));
    });

    test('PG_bytea-Uint8List passes bytes through (no base64)', () {
      expect(
        code,
        contains("avatarBytes = letAsOrNull<Uint8List>(json?['avatar_bytes'])"),
      );
    });

    test('PG_enum + unknownEnumValue wraps the valueOf result with ??', () {
      expect(
        code,
        contains(
          'AuthProviderKindType.values.valueOf'
          "(json?['auth_provider']?.toString())",
        ),
      );
      expect(code, contains('?? AuthProviderKindType.unknown'));
    });

    test('PG_timestamptz uses the DateTime.tryParse chain', () {
      expect(code, contains('DateTime.tryParse(a)?.toUtc()'));
    });

    test('fallback wires to ?? <literal>', () {
      // login_count has fallback: 0
      expect(code, contains("letIntOrNull(json?['login_count']) ?? 0"));
      // is_active has fallback: true
      expect(code, contains("letBoolOrNull(json?['is_active']) ?? true"));
    });
  });

  group('Postgres nested model + jsonb + references', () {
    final code = _read('_model_pg_post.g.dart');

    test('jsonb-Map decodes via letMapOrNull', () {
      expect(code, contains("letMapOrNull<dynamic, dynamic>(json?['extra'])"));
    });

    test('jsonb-Model decodes via letMapOrNull then ModelXxx.fromJson', () {
      expect(code, contains("letMapOrNull<String, dynamic>(json?['metadata'])"));
      expect(code, contains('ModelPostMetadata.fromJson(a)'));
    });

    test('jsonb-Map to-side uses jsonEncode + local alias (no stray p0)', () {
      expect(code, contains('extra0 ='));
      expect(code, contains('jsonEncode(a.map'));
      expect(code, isNot(contains('jsonEncode(p0!.map')));
    });

    test('jsonb-Model to-side uses jsonEncode(toJson())', () {
      expect(code, contains('jsonEncode(metadata!.toJson())'));
    });

    test('PG_enum + unknownEnumValue handles the post status case too', () {
      expect(code, contains('PostStatusKindType.values.valueOf'));
      expect(code, contains('?? PostStatusKindType.draft'));
    });

    test('native PG array decodes via letListOrNull', () {
      expect(code, contains("letListOrNull<dynamic>(json?['tags'])"));
    });
  });

  group('SQLite dialect (DartSqliteTypeMappers)', () {
    final code = _read('_model_sqlite_settings.g.dart');

    test('SQLITE_integer-bool forwards to letBoolOrNull (handles 0/1)', () {
      expect(
        code,
        contains(
          'notificationsEnabled = letBoolOrNull'
          "(json?['notifications_enabled'])",
        ),
      );
    });

    test('SQLITE_integer-bool emits 0/1 on write', () {
      expect(code, contains('notificationsEnabled! ? 1 : 0'));
    });

    test('SQLITE_epochms-DateTime decodes epoch ms', () {
      expect(
        code,
        contains('DateTime.fromMillisecondsSinceEpoch(a, isUtc: true)'),
      );
    });

    test('SQLITE_text-DateTime keeps the ISO 8601 chain', () {
      expect(code, contains('DateTime.tryParse(a)?.toUtc()'));
    });

    test('SQLITE_json-Map jsonEncodes with local alias (no stray p0)', () {
      expect(code, contains('jsonEncode(a.map'));
      expect(code, isNot(contains('jsonEncode(p0!.map')));
    });

    test('SQLITE_blob-Uint8List passes raw bytes', () {
      expect(
        code,
        contains("letAsOrNull<Uint8List>(json?['avatar_cache'])"),
      );
    });

    test('fallback applies to SQLite fields', () {
      expect(code, contains("letBoolOrNull(json?['notifications_enabled']) ?? true"));
      expect(code, contains("?.toString().trim().nullIfEmpty ?? 'system'"));
    });
  });

  group('Firestore dialect (DartFirestoreTypeMappers)', () {
    final code = _read('_model_firestore_doc.g.dart');

    test('FS_timestamp-DateTime converts via Timestamp.toDate().toUtc()', () {
      expect(code, contains('letAsOrNull<Timestamp>'));
      // `dart fix` (run post-generation) collapses the explicit
      // `a != null ? a.toDate()...` ternary into `a?.toDate()...`; we
      // accept either shape.
      expect(
        code.contains('a?.toDate().toUtc()') ||
            code.contains('a.toDate().toUtc()'),
        isTrue,
      );
    });

    test('FS_timestamp-DateTime writes via Timestamp.fromDate', () {
      expect(code, contains('Timestamp.fromDate(capturedAt!.toUtc())'));
    });

    test('FS_server_timestamp-DateTime writes FieldValue.serverTimestamp()', () {
      expect(code, contains('FieldValue.serverTimestamp()'));
    });

    test('FS_geopoint-GeoPoint passes through', () {
      expect(code, contains("letAsOrNull<GeoPoint>(json?['location'])"));
    });

    test('FS_ref-String pulls .path off DocumentReference', () {
      expect(code, contains('letAsOrNull<DocumentReference>'));
      expect(code, contains('a.path'));
    });

    test('FS_blob-Uint8List unwraps Blob.bytes on read', () {
      expect(code, contains('letAsOrNull<Blob>'));
      expect(code, contains('a.bytes'));
    });

    test('FS_blob-Uint8List wraps in Blob() on write', () {
      expect(code, contains('Blob(thumbnail!)'));
    });

    test('back-compat: bare Timestamp still works', () {
      expect(
        code,
        contains("legacyStamp = letAsOrNull<Timestamp>(json?['legacyStamp'])"),
      );
    });
  });

  group('STRICT- direct casts', () {
    final code = _read('_model_strict_dto.g.dart');

    test('STRICT-String emits a direct as-cast', () {
      expect(code, contains("id = json?['id'] as String?"));
      expect(code, contains("name = json?['name'] as String?"));
    });

    test('STRICT-int routes through num for JSON num→int handling', () {
      expect(code, contains("count = (json?['count'] as num?)?.toInt()"));
    });

    test('STRICT-double routes through num', () {
      expect(code, contains("ratio = (json?['ratio'] as num?)?.toDouble()"));
    });

    test('STRICT-bool casts directly', () {
      expect(code, contains("active = json?['active'] as bool?"));
    });

    test('STRICT-DateTime parses without defensive chain', () {
      expect(
        code,
        contains("DateTime.parse(json?['createdAt'] as String).toUtc()"),
      );
    });

    test('STRICT-Uri parses directly', () {
      expect(code, contains("Uri.parse(json?['homepage'] as String)"));
    });

    test('STRICT to-side passes primitives through', () {
      expect(code, contains('final id0 = id;'));
      expect(code, contains('final name0 = name;'));
      expect(code, contains('final count0 = count;'));
    });
  });

  group('Per-field converter slot', () {
    final code = _read('_model_converter_invoice.g.dart');

    test('converter: bypasses dialect mappers and emits direct call', () {
      expect(code, contains("const MoneyConverter().fromJson(json?['total'])"));
    });

    test('converter to-side calls .toJson(field)', () {
      expect(code, contains('const MoneyConverter().toJson(total)'));
    });

    test('other fields are unaffected by the converter on one field', () {
      expect(code, contains("id = json?['id']?.toString().trim().nullIfEmpty"));
    });
  });

  group('Thread (includeInJson/SqlMap flags + jsonb List<Model>)', () {
    final code = _read('_model_thread.g.dart');

    test('PG_jsonb-List<Model> uses letListOrNull on read', () {
      expect(code, contains("letListOrNull<dynamic>(json?['comments'])"));
    });

    test('list of model items invokes nested fromJson per element', () {
      // The collection mapper iterates and applies the per-element mapper.
      // For a model element, that's `ModelComment.fromJson(...)`.
      expect(code, contains('ModelComment.fromJson'));
    });

    test('jsonb-List<Model> to-side wraps each in toJson() + jsonEncodes', () {
      expect(code, contains('jsonEncode'));
      expect(code, contains('toJson()'));
    });

    test('the model still emits Equatable wiring', () {
      expect(code, contains('with EquatableMixin'));
    });

    test('fieldnames class includes the camelCased field names', () {
      expect(code, contains('static const creatorId = '));
      expect(code, contains('static const unreadCount = '));
      expect(code, contains('static const cacheToken = '));
    });
  });
}
